name: CI Pipeline

on: 
  push:
    branches: ["main"]

env:
  API_BASE_URL: 'http://localhost:3000'
  PORT: 4000

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: npm install

      - name: Iniciar servidor de mocks
        run: nohup npm run mock-server > mock-server.log 2>&1 &
        shell: bash

      - name: Aguardar mock server iniciar
        run: npx wait-on http://localhost:3000 --timeout 10000
        shell: bash

      - name: Iniciar aplicação
        run: nohup npm run server > app.log 2>&1 &
        shell: bash

      - name: Aguardar aplicação iniciar
        run: npx wait-on http://localhost:4000 --timeout 10000
        shell: bash

      - name: Executar testes (Cypress)
        run: npx cypress run
